[package]
name = "pdfrs"
version = "0.1.0"
authors = ["Markus Ast <m@rkusa.st>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_pdf = { path = "../serde_pdf" }
uuid = { version = "0.7", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
